### ISSUE TITLE
Add EPD7in5b_V2

### ISSUE THREAD

**Issue by Quotic** [eXoCooLd/Waveshare.EPaperDisplay#10]
(Just for traceability)

So the SKU 17059 on my display seems wrong. It is a EPD7in5b_V2 instead of a EPD7in5b_HD Display.

I started the implementation and testing. 
- some changes in init (related to EPD7in5_V2)
- three colors instead of B/W #

So I have no experience in NUnit, but I will try my best.

**Comment by eXoCooLd** [comment]
Moved discussion to the pull request: Add EPD7in5b_V2 #11
