### ISSUE TITLE
Nuget package

### ISSUE THREAD

**Issue by whihathac** [eXoCooLd/Waveshare.EPaperDisplay#2]
This is super great! Do you have plans to publish a nuget package for the library so it's easy to consume? Do you want help writing one?

**Comment by eXoCooLd** [comment]
Thank you.
I didn't know that there was a demand for a NuGet package :-)
The library can now be fetched with NuGet:
https://www.nuget.org/packages/eXoCooLd.Waveshare.EPaperDisplay/

**Comment by whihathac** [comment]
Amazing! Thank you for such quick response!

**Comment by eXoCooLd** [comment]
You are welcome
