### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by bezysoftware** [eXoCooLd/Waveshare.EPaperDisplay#9]
Hi, thanks for the lib, I was able to get it working with my 7.5" B&W display after two small things:

- Enabling SPI in `raspi-config`
- Installing `libgdiplus` (DllNotFoundException was thrown without it)

It might be worth to put this in some getting started documentation

**Comment by eXoCooLd** [comment]
Hi, you are welcome.
Good point, a "Getting started" in the wiki would be nice.
I will write one for a fresh installed Pi soon :-)

**Comment by Quotic** [comment]
I'm looking forward to it. I tried this one yesterday, but my screen is only refreshing and will not show the image. So a startup guide would be nice. Thanks for your work @eXoCooLd

**Comment by eXoCooLd** [comment]
Quick Setup Guide is done: https://github.com/eXoCooLd/Waveshare.EPaperDisplay/wiki/Quick-Setup

**Comment by Quotic** [comment]
Thank you and I found out yesterday that I have an 7.5" B,W&R Display with "HD"-Resolution so there are many differences in commands to the 2 which are already implemented. I try my best to extend it and try to do a pull request. (will be my first time on github :>)

**Comment by bezysoftware** [comment]
@eXoCooLd Looks good!
